### ISSUE TITLE
Expose peer socket address

### ISSUE THREAD

**Issue by prasannavl** [rust-net-web/http-service#25]
Currently, the `http-service` depends heavily on the only defacto impl of `hyper` - which exposes the peer socket address in it's `Ctx` of the closure that's taken by `MakeServiceFn`. 

Options have to explored to get this into `Request` as an extension, or through other means, so that downstream APIs like tide can expose it subsequently.

**Comment by pickfire** [comment]
Any update on this?

**Comment by yoshuawuyts** [comment]
@pickfire none currently. We could expose a new method on the trait that returns a string by default (because it should be generic over both net and unix addresses), but panics as its default impl so that impls such as Hyper may still work with it.

__edit:__ actually we can probably bypass hyper and provide an impl by getting the peer addr from the TcpStream. Maybe we shouldn't even provide a default impl; though that way it'd be forward-compatible and we wouldn't have to issue a breaking change.

**Comment by yoshuawuyts** [comment]
Something else to consider is that there are different peer addresses possible:

- The address of the unix/tcp connection
- The address passed by `X-Forwarded-For` / `Forwarded` headers

Both might be valuable to track, and we should provide APIs to access both. For example:

```rust
app.at("/", async |req| {
     // First checks any of the "forwarded" headers, then returns the tcp/unix peer addr.
    dbg!(req.peer_addr()?);

    // Returns the tcp/unix peer addr.
    dbg!(req.raw_peer_addr()?);
});

**Comment by yoshuawuyts** [comment]
Closing because we're archiving this repo.
