### ISSUE TITLE
Implement AsyncBufRead for Body

### ISSUE THREAD

**Issue by yoshuawuyts** [rust-net-web/http-service#31]
The `Body` type currently implements `Stream<Item = Bytes>`. This makes it hard to do common actions, such as split by lines (e.g. [`BufReader`](https://docs.rs/futures-preview/0.3.0-alpha.16/futures/io/struct.BufReader.html)), decode using known decoders (e.g. [`async-compression`](https://github.com/rustasync/async-compression)), and other actions we'd expect from a source.

In addition to that the buffers returned by `Stream` are itself unparsed, which means that to do anything useful with them they still need to be parsed. `Stream` doesn't lend itself well to this, while `AsyncRead` was designed for specifically this case.

Instead if the `Body` type implemented `AsyncRead` it would be more convenient to operate on, and treat it just like any other source of bytes (e.g. `File`, `TcpStream`, `Stdin`, etc.)

**Comment by fairingrey** [comment]
I support this! I was actually meaning to open a discussion about it earlier when I was talking with @Nemo157 on how we would implement tide-compression, and I originally remarked that it would be difficult to do without an easier, more sensible approach for what the `Body` should be.

It would currently break a number of things in Tide, but I think this change will definitely pay off in the long run.

EDIT: (scratch this, BufReader supports `AsyncBufRead`)

**Comment by fairingrey** [comment]
@yoshuawuyts As it turns out it should already be pretty easy to convert Body into an `AsyncRead` type via the [`into_async_read`](https://rust-lang-nursery.github.io/futures-api-docs/0.3.0-alpha.16/futures/stream/trait.TryStreamExt.html#method.into_async_read) combinator provided by `TryStreamExt`. This code compiles just fine, as Bytes implements `AsRef<[u8]>`:

```rust
use http_service::Body;
use futures::TryStreamExt;

fn main() {
    let body = Body::empty().into_async_read();
}
```

So `Body` actually already supports `AsyncRead` it turns out -- underneath `Body` isn't actually `Stream<Item = Bytes>` but actually `Stream<Item = Result<Bytes, std::io::Error>>` which in turn is also a `TryStream`... and so on and so forth.

EDIT: Following discussion in the channel, I think I'm supposed to understand this better as "`Body` should support `AsyncRead` in lieu of `Stream`". I'll try playing with this later, hopefully it pans out right!

EDIT 2: It does feel as if I'm going in over my head with this :sweat_smile:

**Comment by Nemo157** [comment]
> Following discussion in the channel, I think I'm supposed to understand this better as "`Body` should support `AsyncRead` in lieu of `Stream`".

That's been my understanding as well. IMO it's a more accurate representation of the interface between an arbitrary HTTP server and a web application. `IntoAsyncRead` can then be used to trivially convert `hyper`'s current `Stream` based representation to match the interface.

One idea might be to use `AsyncBufRead` here as probably all HTTP servers will have buffering already builtin, and forcing use cases like `tide-compression` to then add _another_ layer of buffering will cause unnecessary copying. If there are some HTTP servers that don't have buffering already they can easily wrap their stream in `BufReader`.
